//! VAAPI H.264 parameter-buffer -> internal `EncoderConfig` / `PicParams` mappers.
//!
//! These parsers take a raw byte buffer (as stored in `BufferRec::storage`)
//! and re-interpret it as the corresponding `VAEnc*ParameterBufferH264` struct
//! generated by bindgen. The one unavoidable `unsafe` is the typed pointer
//! cast; we gate it with a length check and with `core::mem::align_of` so a
//! misaligned `Vec<u8>` can never produce a misaligned read.
//!
//! Output types are plain-data and do not touch NVENC or CUDA types, which
//! keeps these parsers fully testable on any host.

#![allow(dead_code)]

use va_sys as va;

/// Projection of an H.264 SPS buffer into the subset we forward to NVENC.
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
pub struct EncoderConfig {
    /// Target bitrate in bits per second. Zero means "not set".
    pub bits_per_second: u32,
    /// IDR period in frames. Zero means "keep encoder default".
    pub idr_period: u32,
    /// Derived frame rate (`time_scale / (num_units_in_tick * 2)`), rounded.
    /// Zero means "not derivable from the VUI timebase".
    pub fps: u32,
    /// Maximum number of reference frames the client asked for.
    pub max_num_ref_frames: u32,
    /// Decoded picture dimensions, in pixels (MB count × 16).
    pub width: u32,
    pub height: u32,
    /// `level_idc`. `profile_idc` is carried via the VAConfig (not the SPS).
    pub level_idc: u8,
}

/// Projection of an H.264 picture parameter buffer.
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
pub struct PicParams {
    /// Force this frame to be an IDR (random-access point).
    pub force_idr: bool,
    /// Initial QP (used by NVENC ConstQP rate control).
    pub pic_init_qp: u32,
    /// `coded_buf` VA-ID from `VAEncPictureParameterBufferH264::coded_buf` —
    /// the buffer into which `vaEndPicture` should write the bitstream.
    pub coded_buf: u32,
}

/// Parse the raw bytes of a `VAEncSequenceParameterBufferType` buffer.
///
/// Returns `None` if the buffer is too small or unaligned. An unaligned buffer
/// can happen if the client passed a sub-slice view — we conservatively refuse
/// rather than invoke UB via a misaligned read.
pub fn parse_sps(bytes: &[u8]) -> Option<EncoderConfig> {
    let size = core::mem::size_of::<va::VAEncSequenceParameterBufferH264>();
    let align = core::mem::align_of::<va::VAEncSequenceParameterBufferH264>();
    if bytes.len() < size { return None; }
    if (bytes.as_ptr() as usize) % align != 0 { return None; }

    // SAFETY: length + alignment checked above; the bindgen struct is
    // `#[repr(C)]` plain-old-data (no pointers), so re-interpreting the
    // client-provided bytes is well-defined.
    let sps: &va::VAEncSequenceParameterBufferH264 =
        unsafe { &*(bytes.as_ptr() as *const va::VAEncSequenceParameterBufferH264) };

    // VAAPI timebase convention (see va_enc_h264.h):
    //     frame_rate = time_scale / (num_units_in_tick * 2)
    // Guard against degenerate zero inputs.
    let fps = if sps.num_units_in_tick > 0 && sps.time_scale > 0 {
        let raw = sps.time_scale as u64 / (sps.num_units_in_tick as u64 * 2);
        raw.min(u32::MAX as u64) as u32
    } else {
        0
    };

    Some(EncoderConfig {
        bits_per_second: sps.bits_per_second,
        idr_period: sps.intra_idr_period,
        fps,
        max_num_ref_frames: sps.max_num_ref_frames,
        width: (sps.picture_width_in_mbs as u32) * 16,
        height: (sps.picture_height_in_mbs as u32) * 16,
        level_idc: sps.level_idc,
    })
}

/// Parse the raw bytes of a `VAEncPictureParameterBufferType` buffer.
pub fn parse_pps(bytes: &[u8]) -> Option<PicParams> {
    let size = core::mem::size_of::<va::VAEncPictureParameterBufferH264>();
    let align = core::mem::align_of::<va::VAEncPictureParameterBufferH264>();
    if bytes.len() < size { return None; }
    if (bytes.as_ptr() as usize) % align != 0 { return None; }

    // SAFETY: length + alignment checked; bindgen struct is POD repr(C).
    let pps: &va::VAEncPictureParameterBufferH264 =
        unsafe { &*(bytes.as_ptr() as *const va::VAEncPictureParameterBufferH264) };

    // `idr_pic_flag` is a single bit inside the `pic_fields` bitfield union.
    // bindgen wraps union fields in `__BindgenUnionField<T>` when the inner
    // type isn't Copy; `as_ref()` is the documented accessor.
    // SAFETY: `bits` is always a valid alternative of the bindgen-generated
    // union (all variants share the same raw storage).
    let idr = unsafe { pps.pic_fields.bits.as_ref().idr_pic_flag() } != 0;
    Some(PicParams {
        force_idr: idr,
        pic_init_qp: pps.pic_init_qp as u32,
        coded_buf: pps.coded_buf,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fresh_sps() -> Box<va::VAEncSequenceParameterBufferH264> {
        // SAFETY: struct is POD repr(C); zero is a valid bit pattern.
        Box::new(unsafe { core::mem::zeroed() })
    }

    fn bytes_of<T>(t: &T) -> &[u8] {
        // SAFETY: POD struct; reading the byte representation is sound.
        unsafe {
            core::slice::from_raw_parts((t as *const T) as *const u8, core::mem::size_of::<T>())
        }
    }

    #[test]
    fn sps_extracts_bitrate_fps_and_dimensions() {
        let mut sps = fresh_sps();
        sps.bits_per_second = 3_000_000;
        sps.intra_idr_period = 120;
        sps.max_num_ref_frames = 1;
        sps.picture_width_in_mbs = 120; // 1920 / 16
        sps.picture_height_in_mbs = 68; // 1080 / 16, rounded up
        sps.level_idc = 42;
        sps.num_units_in_tick = 1;
        sps.time_scale = 120; // => fps = 60
        let cfg = parse_sps(bytes_of(&*sps)).expect("parses");
        assert_eq!(cfg.bits_per_second, 3_000_000);
        assert_eq!(cfg.idr_period, 120);
        assert_eq!(cfg.fps, 60);
        assert_eq!(cfg.max_num_ref_frames, 1);
        assert_eq!(cfg.width, 1920);
        assert_eq!(cfg.height, 1088);
        assert_eq!(cfg.level_idc, 42);
    }

    #[test]
    fn sps_with_zero_timebase_yields_fps_zero_not_panic() {
        let sps = fresh_sps();
        let cfg = parse_sps(bytes_of(&*sps)).expect("parses");
        assert_eq!(cfg.fps, 0);
    }

    #[test]
    fn sps_too_short_returns_none() {
        let bytes = [0u8; 4];
        assert!(parse_sps(&bytes).is_none());
    }

    #[test]
    fn pps_too_short_returns_none() {
        let bytes = [0u8; 4];
        assert!(parse_pps(&bytes).is_none());
    }

    #[test]
    fn pps_without_idr_flag_parses_as_non_idr() {
        // SAFETY: POD.
        let pps: Box<va::VAEncPictureParameterBufferH264> =
            Box::new(unsafe { core::mem::zeroed() });
        let p = parse_pps(bytes_of(&*pps)).expect("parses");
        assert!(!p.force_idr);
    }

    #[test]
    fn pps_with_idr_flag_set() {
        // SAFETY: POD.
        let mut pps: Box<va::VAEncPictureParameterBufferH264> =
            Box::new(unsafe { core::mem::zeroed() });
        // SAFETY: `bits` is a valid variant of the bindgen-generated union.
        unsafe { pps.pic_fields.bits.as_mut().set_idr_pic_flag(1) };
        pps.pic_init_qp = 28;
        pps.coded_buf = 0x1234_5678;
        let p = parse_pps(bytes_of(&*pps)).expect("parses");
        assert!(p.force_idr);
        assert_eq!(p.pic_init_qp, 28);
        assert_eq!(p.coded_buf, 0x1234_5678);
    }
}
